Require construct 2.9 specifically
If you have construct 2.8 installed from before, `pip3 install git+https://github.com/0x0L/rocksmith.git` will work, but then when you try to unpack a package, you get this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyrocksmith", line 6, in <module>
    from rocksmith.command_line import main
  File "/usr/local/lib/python3.7/site-packages/rocksmith/__init__.py", line 2, in <module>
    from .sng import SNG
  File "/usr/local/lib/python3.7/site-packages/rocksmith/sng.py", line 38, in <module>
    'name' / PaddedString(32, encoding='utf8')
NameError: name 'PaddedString' is not defined
```
 
Uninstalling `construct` and reinstalling to get the 2.9 fixed it.

I *think* this change to would make it so it works out of the box, but I'm not sure - I'm not much of a pythonist..